# Generated by Django 5.0.6 on 2024-06-10 23:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_article_commenttoarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttoarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commenttoarticle',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='CommentToArticle',
        ),
    ]
